const RESULT_CODES = Object.freeze({
    SUCCESS: 'Success',
    EMAIL_ALREADY_REGISTERED: 'Ya existe un usuario registrado con ese email',
    LIKE_ALREADY_REGISTERED: 'LIKE_ALREADY_REGISTERED',
    CATEGORY_ALREADY_REGISTERED: 'La categoria ya existe',
    PASSWORD_NO_MATCH: 'PASSWORD_NO_MATCH',
    PASSWORD_MUST_HAVE_8_CHARACTERS: 'PASSWORD_MUST_HAVE_8_CHARACTERS',
    NO_USERS_REGISTERED: 'NO_USERS_REGISTERED',
    NO_POSTS_REGISTERED: 'NO_POSTS_REGISTERED',
    NO_COMMENTS_REGISTERED: 'NO_COMMENTS_REGISTERED',
    PRODUCT_NOT_FOUND: 'El producto no existe',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    LIKE_NOT_FOUND: 'LIKE_NOT_FOUND',
    NO_FOLLOW_THIS_USER: 'NO_FOLLOW_THIS_USER',
    YOU_CANNOT_FOLLOW_YOURSELF: 'YOU_CANNOT_FOLLOW_YOURSELF',
    YOU_CANNOT_MAKE_THIS_ACTION: 'No puedes realizar esta accion'
  });
  
  module.exports = {
    RESULT_CODES,
  };